blank_issues_enabled: false
contact_links:
  - name: Questions / General Discussion
    url: https://github.com/Simicedev/course-assignmentJS-fall-2025/discussions
    about: Please ask and answer questions here.